services:
  db:
    container_name: db
    image: postgres:alpine
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pg-data:/var/lib/postgresql/data


volumes:
  pg-data:

